// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ForecastCard: typeof import('./components/ForecastCard.vue')['default']
    ForecastCards: typeof import('./components/ForecastCards.vue')['default']
    ForecastImg: typeof import('./components/ForecastImg.vue')['default']
    ForecastNavTab: typeof import('./components/ForecastNavTab.vue')['default']
    ForecastPlot: typeof import('./components/ForecastPlot.vue')['default']
    ForecastSidebar: typeof import('./components/ForecastSidebar.vue')['default']
    GraphBarChart: typeof import('./components/graph/BarChart.vue')['default']
    GraphDotLabels: typeof import('./components/graph/DotLabels.vue')['default']
    GraphLinePlot: typeof import('./components/graph/LinePlot.vue')['default']
    GraphXAxis: typeof import('./components/graph/XAxis.vue')['default']
    GraphYAxis: typeof import('./components/graph/YAxis.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteDropDown: typeof import('./components/SiteDropDown.vue')['default']
  }
}
